### ISSUE TITLE
Warnings on npm install

### ISSUE THREAD

**Issue by karmatosed** [Automattic/Picard#44]
I got the following:

> npm WARN optional dep failed, continuing fsevents@0.3.8
> node-sass@2.1.1 install /Users/karmatosed/Vagrant-sites/vagrant-local/www/restplay/htdocs/wp-content/themes/Picard/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js
> 
> node-sass@2.1.1 postinstall /Users/karmatosed/Vagrant-sites/vagrant-local/www/restplay/htdocs/wp-content/themes/Picard/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

**Comment by karmatosed** [comment]
I also got this incase it's also something:

`SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/karmatosed/Vagrant-sites/vagrant-local/www/restplay/htdocs/wp-content/themes/Picard/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things`
