### ISSUE TITLE
gulp build fails with AssertionError: missing path

### ISSUE THREAD

**Issue by musen** [Automattic/Picard#53]
[13:10:35] Using gulpfile C:\Ampps\www\wpdev\wp-content\themes\Picard\gulpfile.js
[13:10:35] Starting 'styles'...
[13:10:35] 'styles' errored after 32 ms
[13:10:35] AssertionError: missing path
    at Module.require (module.js:352:3)
    at require (internal/module.js:12:17)
    at requireFn (C:\Ampps\www\wpdev\wp-content\themes\Picard\node_modules\gulp-load-plugins\index.js:37:14)
    at Object.defineProperty.get (C:\Ampps\www\wpdev\wp-content\themes\Picard\node_modules\gulp-load-plugins\index.js:59:18)
    at Gulp.<anonymous> (C:\Ampps\www\wpdev\wp-content\themes\Picard\gulp\styles.js:5:10)
    at module.exports (C:\Ampps\www\wpdev\wp-content\themes\Picard\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Ampps\www\wpdev\wp-content\themes\Picard\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Ampps\www\wpdev\wp-content\themes\Picard\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Ampps\www\wpdev\wp-content\themes\Picard\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Muluneh\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned^3.7.0\index.js:46:20

**Comment by ajiahub** [comment]
are you ok?
